name: Lint and format code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install portaudio19-dev python3-pyaudio
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-deps
        pip install pylint
    - name: Running Black formatter
      run: |
        black . -t py39
        git commit -m "Code reformatted by Black" && git push || echo "No changes to commit"
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
        
